In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('logistics_dataset_uncleaned.csv')

In [3]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,NaN,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9997,S684607,O29085,C5106,Li Wei,jane@,917647185930,Chennai,NaN,NaN,400001.0,...,8138.839000,168.366458,Warehouse B,Central,NaN,Low,NaN,NaN,Not Returned,Delayed delivery
9998,S145436,O48653,C4340,Amit Kumar,NaN,919825431142,Chennai,USA,East,NaN,...,8231.461695,643.200256,Warehouse A,NaN,Ms. Verma,Low,Debet,No,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [4]:
df.duplicated('Shipment_ID')

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [5]:
df=df.drop_duplicates('Shipment_ID')

In [6]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,NaN,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9997,S684607,O29085,C5106,Li Wei,jane@,917647185930,Chennai,NaN,NaN,400001.0,...,8138.839000,168.366458,Warehouse B,Central,NaN,Low,NaN,NaN,Not Returned,Delayed delivery
9998,S145436,O48653,C4340,Amit Kumar,NaN,919825431142,Chennai,USA,East,NaN,...,8231.461695,643.200256,Warehouse A,NaN,Ms. Verma,Low,Debet,No,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [7]:
df.duplicated('Order_ID')

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998     True
9999    False
Length: 9948, dtype: bool

In [8]:
df=df.drop_duplicates('Order_ID')

In [9]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,NaN,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9997,S684607,O29085,C5106,Li Wei,jane@,917647185930,Chennai,NaN,NaN,400001.0,...,8138.839000,168.366458,Warehouse B,Central,NaN,Low,NaN,NaN,Not Returned,Delayed delivery
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [10]:
df.duplicated(subset=['Customer_ID','Email'])

0       False
1       False
2       False
3       False
4       False
        ...
9994    False
9995    False
9996    False
9997     True
9999    False
Length: 9413, dtype: bool

In [11]:
df=df.drop_duplicates(subset=['Customer_ID','Email'])

In [12]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,NaN,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,NaN,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [13]:
df["City"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2763263256.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("Unknown",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2763263256.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"].fillna("Unknown",inplace=True)

In [14]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,NaN,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [15]:
df["Country"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\982552147.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Country"].fillna("Unknown",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\982552147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Country"].fillna("Unknown",inplace=True)

In [16]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [17]:
df["Category"].fillna("Misc",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3439075271.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Category"].fillna("Misc",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3439075271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"].fillna("Misc",inplace=True)

In [18]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [19]:
x = df["Weight_kg"].mean()
df.fillna({"Weight_kg": x}, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3793572486.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna({"Weight_kg": x}, inplace=True)

In [20]:
x

np.float64(46.370715781593645)

In [21]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [22]:
df["Delivery_Mode"].fillna("road",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3904423890.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Delivery_Mode"].fillna("road",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3904423890.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Delivery_Mode"].fillna("road",inplace=True)

In [23]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [24]:
df["Fuel_Cost"].fillna(df.groupby("Transport_Type")["Fuel_Cost"].transform("median"),inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\988851821.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Fuel_Cost"].fillna(df.groupby("Transport_Type")["Fuel_Cost"].transform("median"),inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\988851821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fuel_Cost"].fillna(df.groupby("Transport_Type")["Fuel_Cost"].transform("median"),inplace=True)

In [25]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,NaN
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,NaN
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,NaN
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,NaN
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,NaN
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,NaN
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,NaN

In [26]:
df["Remarks"].fillna("No Remarks",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3973173657.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Remarks"].fillna("No Remarks",inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3973173657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Remarks"].fillna("No Remarks",inplace=True)

In [27]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,No Remarks
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,No Remarks
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,No Remarks

In [28]:
df = df[df["Quantity"]>0]

In [29]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,No Remarks
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,No Remarks
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,No Remarks

In [30]:
df = df[df["Weight_kg"]>0]

In [31]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,No Remarks
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,No Remarks
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,No Remarks

In [32]:
df=df[df['Total_Price']>0]

In [33]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
0,S981356,O13241,C2917,Jane Smith,jane@,916827957610,Chennai,UK,West,110001.0,...,7342.820681,1779.594970,NaN,South Hub,Mr. Patel,NaN,Card,Yes,Pending,No Remarks
1,S316311,O56814,C9290,Jane Smith,NaN,918882137895,Delhi,U.K.,East,NaN,...,5630.916919,419.635432,NaN,Central,Mr. Patel,NaN,Cash,Yes,NaN,No Remarks
2,S470009,O66124,C1239,Amit Kumar,amit@gmail.com,916621089428,Delhi,U.K.,West,560001.0,...,8641.039995,1267.012215,Warehouse A,South Hub,Mr. Patel,High,Online,No,Not Returned,Delayed delivery
3,S459529,O28293,C5966,michael brown,jane@,918061558996,Bangalore,India,North,110001.0,...,3845.086369,1463.660290,Hub C,North Hub,Ms. Verma,NaN,Online,Yes,NaN,Delayed delivery
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
9999,S167942,O97916,C2233,John Doe,jane@,916003267313,Chennai,India,South,110001.0,...,3845.086369,433.142868,Warehouse A,Central,Mr. Patel,NaN,Credt,NaN,Pending,No Remarks

In [34]:
df = df[df["Delivery_Date"] >= df["Shipment_Date"]]

In [35]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debet,Yes,Pending,No Remarks
12,S451621,O15692,C4872,Fatima Noor,jane@,919468252530,Unknown,us,West,110001.0,...,3152.005782,433.142868,NaN,South Hub,Ms. Verma,High,Credt,Yes,Pending,No Remarks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks

In [36]:
df=df[df['Delay_Days']>=-1]

In [37]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debet,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debet,NaN,Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credt,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks

In [38]:
df["Payment_Mode"]=df["Payment_Mode"].replace({"Credt":"Credit","Debet":"Debit"})

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2191643360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Mode"]=df["Payment_Mode"].replace({"Credt":"Credit","Debet":"Debit"})

In [39]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks

In [40]:
df["Status"]=df["Status"].replace({"delayed":"Delayed","DELAYED":"Delayed"})

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\973456718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Status"]=df["Status"].replace({"delayed":"Delayed","DELAYED":"Delayed"})

In [41]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks

In [42]:
df["Country"]=df["Country"].replace({"us":"USA","U.K.":"UK"})

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2560690752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Country"]=df["Country"].replace({"us":"USA","U.K.":"UK"})

In [43]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
4,S372486,O40352,C6710,Fatima Noor,NaN,919316399195,Bangalore,Unknown,South,400001.0,...,7342.820681,1384.774596,Warehouse B,South Hub,Ms. Verma,Low,NaN,No,Not Returned,Handle with care
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9994,S274987,O34297,C3828,Amit Kumar,NaN,916274817938,mumbai,india,West,600001.0,...,8553.133891,149.423824,Warehouse B,South Hub,Ms. Verma,NaN,Card,NaN,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks
9996,S703532,O14424,C5315,Fatima Noor,NaN,916601318697,Delhi,india,East,NaN,...,9984.617643,731.066440,Warehouse B,North Hub,NaN,High,Cash,Yes,Returned,No Remarks

In [44]:
df=df[df["Email"].str.contains("@", na=False)]

In [45]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,8607.492526,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,5675.666106,107.634806,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks

In [46]:
df=df[df["Distance_km"]<=2000]

In [47]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,8607.492526,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,5675.666106,107.634806,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks

In [48]:
df[df["Delay_Days"]>5]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,8607.492526,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care
17,S789076,O58826,C3367,Li Wei,amit@gmail.com,916820876325,Unknown,india,North,400001.0,...,2530.987075,1267.012215,Warehouse A,North Hub,Ms. Verma,Medium,Debit,Yes,Pending,Check packaging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9951,S661479,O83798,C7758,michael brown,john@example.com,917457554481,Mumbai,USA,NaN,600001.0,...,2892.410615,309.926701,Warehouse B,South Hub,Ms. Verma,Medium,Debit,NaN,Pending,No Remarks
9957,S538834,O66101,C7612,Amit Kumar,amit@gmail.com,917884029731,Delhi,india,South,400001.0,...,8813.090633,474.580487,Warehouse A,North Hub,NaN,Low,NaN,No,NaN,No Remarks
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks

In [49]:
df[df["Order_Priority"]=="High"]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,352.525220,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
31,S794002,O70026,C8875,Li Wei,john@example.com,917792931815,Unknown,Unknown,NaN,600001.0,...,4344.411364,365.217846,NaN,South Hub,Ms. Verma,High,Online,Yes,Not Returned,No Remarks
48,S196122,O90267,C7159,NaN,amit@gmail.com,918646141901,Unknown,india,West,110001.0,...,2892.410615,1147.606724,Hub C,South Hub,Mr. Patel,High,Online,No,Returned,Handle with care
53,S348688,O42617,C3793,michael brown,amit@gmail.com,916379721447,Chennai,UK,East,560001.0,...,7561.095208,959.330599,NaN,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9892,S568969,O72984,C6794,John Doe,john@example.com,918428783876,Unknown,UK,South,NaN,...,3219.920606,490.745004,Warehouse A,Central,NaN,High,Credit,Yes,NaN,Check packaging
9899,S224168,O96198,C2060,Amit Kumar,jane@,918001718408,Bangalore,India,South,400001.0,...,8337.453157,1463.660290,Hub C,South Hub,Ms. Verma,High,Credit,NaN,Returned,Delayed delivery
9947,S806319,O85510,C3241,Jane Smith,john@example.com,917092825637,Bangalore,USA,East,NaN,...,6853.332809,914.071878,Hub C,South Hub,Mr. Patel,High,Credit,NaN,Returned,Handle with care
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,7652.798286,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks

In [50]:
df[df["Delivery_Mode"]=="Air"]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
17,S789076,O58826,C3367,Li Wei,amit@gmail.com,916820876325,Unknown,india,North,400001.0,...,2530.987075,1267.012215,Warehouse A,North Hub,Ms. Verma,Medium,Debit,Yes,Pending,Check packaging
25,S777803,O75666,C9408,NaN,jane@,919138121270,Delhi,USA,South,NaN,...,9138.029149,787.008748,Warehouse B,Central,Mr. Patel,Low,UPI,NaN,NaN,Check packaging
40,S478286,O88231,C3295,NaN,amit@gmail.com,917364597783,Bangalore,USA,North,560001.0,...,2530.987075,939.145591,Warehouse A,South Hub,Mr. Khan,Low,Cash,NaN,Pending,Check packaging
50,S275615,O56142,C4762,Jane Smith,jane@,919507190470,Chennai,USA,North,560001.0,...,6663.056267,1406.512023,Hub C,Central,Ms. Verma,Low,Credit,NaN,Not Returned,No Remarks
67,S440122,O85883,C2314,michael brown,jane@,918121121069,Mumbai,UK,West,NaN,...,4839.546420,787.008748,Hub C,NaN,NaN,NaN,Credit,Yes,Not Returned,Delayed delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9912,S657504,O31803,C8772,Li Wei,amit@gmail.com,917828038849,mumbai,Unknown,NaN,400001.0,...,103.956957,1114.660511,Hub C,North Hub,Mr. Patel,NaN,Online,NaN,Returned,Check packaging
9913,S578942,O41717,C1962,NaN,jane@,919408345371,Mumbai,USA,North,NaN,...,3495.816486,385.692790,Hub C,NaN,Ms. Verma,NaN,UPI,Yes,Not Returned,Check packaging
9951,S661479,O83798,C7758,michael brown,john@example.com,917457554481,Mumbai,USA,NaN,600001.0,...,2892.410615,309.926701,Warehouse B,South Hub,Ms. Verma,Medium,Debit,NaN,Pending,No Remarks
9956,S551574,O80763,C9492,NaN,john@example.com,919162802758,Mumbai,USA,NaN,NaN,...,8916.361693,1134.787063,Warehouse A,Central,Mr. Khan,Medium,Card,No,NaN,Check packaging
9965,S496316,O60913,C2565,Amit Kumar,amit@gmail.com,917592835375,Chennai,UK,North,560001.0,...,9768.548903,1406.512023,Hub C,South Hub,Ms. Verma,NaN,Debit,NaN,Returned,Check packaging

In [51]:
df[df["Fuel_Cost"]>8000]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,8607.492526,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care
22,S476484,O24048,C7410,NaN,amit@gmail.com,916066672764,mumbai,UK,South,400001.0,...,8553.133891,173.606764,Warehouse A,South Hub,Mr. Khan,NaN,Debit,NaN,NaN,No Remarks
24,S976996,O72852,C9298,Li Wei,amit@gmail.com,919228642734,mumbai,USA,West,400001.0,...,8138.839000,1248.440028,Warehouse A,NaN,Mr. Khan,Medium,Card,NaN,NaN,Check packaging
25,S777803,O75666,C9408,NaN,jane@,919138121270,Delhi,USA,South,NaN,...,9138.029149,787.008748,Warehouse B,Central,Mr. Patel,Low,UPI,NaN,NaN,Check packaging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9911,S900704,O28416,C5210,Fatima Noor,john@example.com,919954014041,Chennai,USA,South,110001.0,...,8565.430964,1406.512023,Warehouse A,North Hub,Mr. Khan,NaN,Card,No,NaN,Check packaging
9956,S551574,O80763,C9492,NaN,john@example.com,919162802758,Mumbai,USA,NaN,NaN,...,8916.361693,1134.787063,Warehouse A,Central,Mr. Khan,Medium,Card,No,NaN,Check packaging
9957,S538834,O66101,C7612,Amit Kumar,amit@gmail.com,917884029731,Delhi,india,South,400001.0,...,8813.090633,474.580487,Warehouse A,North Hub,NaN,Low,NaN,No,NaN,No Remarks
9965,S496316,O60913,C2565,Amit Kumar,amit@gmail.com,917592835375,Chennai,UK,North,560001.0,...,9768.548903,1406.512023,Hub C,South Hub,Ms. Verma,NaN,Debit,NaN,Returned,Check packaging
9972,S270082,O35307,C8275,Amit Kumar,amit@gmail.com,919690306871,Mumbai,Unknown,East,400001.0,...,8013.277385,1000.220882,NaN,South Hub,Mr. Patel,Medium,UPI,Yes,Not Returned,Handle with care

In [52]:
df[df["Total_Price"]>100000]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,8607.492526,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care
22,S476484,O24048,C7410,NaN,amit@gmail.com,916066672764,mumbai,UK,South,400001.0,...,8553.133891,173.606764,Warehouse A,South Hub,Mr. Khan,NaN,Debit,NaN,NaN,No Remarks
24,S976996,O72852,C9298,Li Wei,amit@gmail.com,919228642734,mumbai,USA,West,400001.0,...,8138.839000,1248.440028,Warehouse A,NaN,Mr. Khan,Medium,Card,NaN,NaN,Check packaging
31,S794002,O70026,C8875,Li Wei,john@example.com,917792931815,Unknown,Unknown,NaN,600001.0,...,4344.411364,365.217846,NaN,South Hub,Ms. Verma,High,Online,Yes,Not Returned,No Remarks
33,S617814,O77010,C1177,John Doe,amit@gmail.com,919181497573,Delhi,India,NaN,400001.0,...,7015.422873,151.024447,NaN,Central,NaN,NaN,Cash,Yes,NaN,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9940,S965290,O87888,C9523,John Doe,jane@,916032365264,Chennai,Unknown,West,400001.0,...,1183.948113,826.881871,NaN,South Hub,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
9972,S270082,O35307,C8275,Amit Kumar,amit@gmail.com,919690306871,Mumbai,Unknown,East,400001.0,...,8013.277385,1000.220882,NaN,South Hub,Mr. Patel,Medium,UPI,Yes,Not Returned,Handle with care
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks

In [53]:
df[df["Status"]=="Delayed"]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
26,S687190,O54768,C1407,Amit Kumar,john@example.com,917433943989,Chennai,India,South,400001.0,...,7342.820681,632.826018,NaN,North Hub,Mr. Khan,Low,Online,No,NaN,No Remarks
31,S794002,O70026,C8875,Li Wei,john@example.com,917792931815,Unknown,Unknown,NaN,600001.0,...,4344.411364,365.217846,NaN,South Hub,Ms. Verma,High,Online,Yes,Not Returned,No Remarks
49,S813801,O57535,C8550,NaN,jane@,917866700460,Chennai,India,South,400001.0,...,1320.681108,1335.386338,Warehouse A,NaN,Ms. Verma,Low,UPI,Yes,NaN,No Remarks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9907,S675484,O62797,C7081,Li Wei,john@example.com,917626902179,Mumbai,India,East,600001.0,...,5719.099567,1513.852223,Warehouse A,Central,Mr. Khan,Medium,NaN,Yes,NaN,Handle with care
9910,S389541,O53676,C2031,John Doe,amit@gmail.com,916467136306,Bangalore,UK,East,560001.0,...,5468.341619,1507.020937,Warehouse B,North Hub,Mr. Patel,NaN,Card,Yes,Pending,Handle with care
9911,S900704,O28416,C5210,Fatima Noor,john@example.com,919954014041,Chennai,USA,South,110001.0,...,8565.430964,1406.512023,Warehouse A,North Hub,Mr. Khan,NaN,Card,No,NaN,Check packaging
9913,S578942,O41717,C1962,NaN,jane@,919408345371,Mumbai,USA,North,NaN,...,3495.816486,385.692790,Hub C,NaN,Ms. Verma,NaN,UPI,Yes,Not Returned,Check packaging
9947,S806319,O85510,C3241,Jane Smith,john@example.com,917092825637,Bangalore,USA,East,NaN,...,6853.332809,914.071878,Hub C,South Hub,Mr. Patel,High,Credit,NaN,Returned,Handle with care

In [54]:
df[(df["Country"]=="India") & (df["Total_Price"]>50000)]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
33,S617814,O77010,C1177,John Doe,amit@gmail.com,919181497573,Delhi,India,NaN,400001.0,...,7015.422873,151.024447,NaN,Central,NaN,NaN,Cash,Yes,NaN,Handle with care
47,S308976,O16003,C2855,Fatima Noor,john@example.com,917499940564,Bangalore,India,East,560001.0,...,5630.916919,1229.741794,Warehouse B,Central,Mr. Khan,Low,UPI,Yes,NaN,Handle with care
49,S813801,O57535,C8550,NaN,jane@,917866700460,Chennai,India,South,400001.0,...,1320.681108,1335.386338,Warehouse A,NaN,Ms. Verma,Low,UPI,Yes,NaN,No Remarks
91,S440194,O11390,C1349,Li Wei,amit@gmail.com,917351830514,Delhi,India,NaN,110001.0,...,6203.769968,643.200256,Warehouse B,South Hub,Ms. Verma,Low,Credit,NaN,Returned,Delayed delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9779,S228703,O79991,C8381,NaN,jane@,916001848650,Chennai,India,North,400001.0,...,5873.870748,740.970151,Warehouse A,North Hub,Mr. Patel,Medium,Online,NaN,NaN,Check packaging
9844,S737563,O25479,C2975,John Doe,jane@,919108052065,Mumbai,India,South,NaN,...,9768.548903,1456.701958,Warehouse A,NaN,NaN,Low,Card,Yes,Not Returned,Handle with care
9882,S543673,O47797,C5770,NaN,amit@gmail.com,919185688543,Chennai,India,North,400001.0,...,6919.232083,1053.600666,Hub C,Central,Mr. Khan,High,UPI,Yes,Returned,No Remarks
9907,S675484,O62797,C7081,Li Wei,john@example.com,917626902179,Mumbai,India,East,600001.0,...,5719.099567,1513.852223,Warehouse A,Central,Mr. Khan,Medium,NaN,Yes,NaN,Handle with care
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care

In [55]:
df[df["Insurance"]=="Yes"]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,8916.361693,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,6853.332809,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
17,S789076,O58826,C3367,Li Wei,amit@gmail.com,916820876325,Unknown,india,North,400001.0,...,2530.987075,1267.012215,Warehouse A,North Hub,Ms. Verma,Medium,Debit,Yes,Pending,Check packaging
20,S618003,O67221,C2313,michael brown,amit@gmail.com,918979222732,Chennai,Unknown,East,600001.0,...,6853.332809,709.655395,Hub C,NaN,Ms. Verma,Medium,Credit,Yes,Pending,No Remarks
31,S794002,O70026,C8875,Li Wei,john@example.com,917792931815,Unknown,Unknown,NaN,600001.0,...,4344.411364,365.217846,NaN,South Hub,Ms. Verma,High,Online,Yes,Not Returned,No Remarks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9913,S578942,O41717,C1962,NaN,jane@,919408345371,Mumbai,USA,North,NaN,...,3495.816486,385.692790,Hub C,NaN,Ms. Verma,NaN,UPI,Yes,Not Returned,Check packaging
9940,S965290,O87888,C9523,John Doe,jane@,916032365264,Chennai,Unknown,West,400001.0,...,1183.948113,826.881871,NaN,South Hub,Mr. Patel,Low,Debit,Yes,Pending,No Remarks
9972,S270082,O35307,C8275,Amit Kumar,amit@gmail.com,919690306871,Mumbai,Unknown,East,400001.0,...,8013.277385,1000.220882,NaN,South Hub,Mr. Patel,Medium,UPI,Yes,Not Returned,Handle with care
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,5675.666106,107.634806,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,3087.753105,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care

In [56]:
df[(df["Category"]=="Electronics")&(df["Delivery_Mode"]=="Air")]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
137,S362430,O85256,C2062,Amit Kumar,amit@gmail.com,917001605361,Delhi,USA,West,600001.0,...,8621.622057,1248.440028,Warehouse A,South Hub,Mr. Khan,Medium,Debit,NaN,Not Returned,No Remarks
643,S689694,O23014,C9104,Jane Smith,jane@,917581413376,mumbai,USA,West,400001.0,...,178.809623,1513.852223,Hub C,South Hub,Mr. Patel,NaN,Debit,Yes,Not Returned,No Remarks
720,S321694,O85059,C8400,John Doe,jane@,919035501379,Mumbai,india,East,110001.0,...,7561.095208,1134.787063,Warehouse B,Central,Mr. Patel,High,Cash,Yes,Not Returned,No Remarks
738,S562265,O38745,C7853,Fatima Noor,jane@,917928482145,Bangalore,USA,West,400001.0,...,5527.842774,897.122187,Hub C,South Hub,Ms. Verma,Low,Credit,NaN,Returned,Check packaging
795,S101854,O48106,C1226,John Doe,john@example.com,917218355595,Bangalore,Unknown,NaN,NaN,...,1209.503401,804.018919,Hub C,NaN,Mr. Patel,High,Online,Yes,Pending,Handle with care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013,S593270,O36847,C6689,John Doe,john@example.com,916170011950,Chennai,USA,North,400001.0,...,1034.190411,1314.811892,NaN,Central,Mr. Patel,High,Credit,NaN,Not Returned,No Remarks
9397,S859756,O43762,C2196,NaN,amit@gmail.com,918516035499,Mumbai,india,NaN,110001.0,...,7753.704802,1165.597811,Hub C,South Hub,Mr. Patel,Low,Credit,NaN,Not Returned,Check packaging
9440,S115450,O33980,C7428,John Doe,jane@,918696288710,Mumbai,india,NaN,NaN,...,4493.931902,787.008748,NaN,South Hub,NaN,Low,Card,No,NaN,Handle with care
9524,S910337,O12242,C9827,NaN,john@example.com,917788685576,mumbai,USA,South,110001.0,...,7599.699297,1954.873446,Warehouse A,Central,NaN,NaN,NaN,NaN,NaN,Handle with care
9951,S661479,O83798,C7758,michael brown,john@example.com,917457554481,Mumbai,USA,NaN,600001.0,...,2892.410615,309.926701,Warehouse B,South Hub,Ms. Verma,Medium,Debit,NaN,Pending,No Remarks

In [57]:
df[df["Return_Status"]=="Returned"]

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Fuel_Cost,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,6663.056267,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care
48,S196122,O90267,C7159,NaN,amit@gmail.com,918646141901,Unknown,india,West,110001.0,...,2892.410615,1147.606724,Hub C,South Hub,Mr. Patel,High,Online,No,Returned,Handle with care
53,S348688,O42617,C3793,michael brown,amit@gmail.com,916379721447,Chennai,UK,East,560001.0,...,7561.095208,959.330599,NaN,North Hub,NaN,High,Cash,Yes,Returned,No Remarks
75,S500169,O57638,C6761,John Doe,jane@,918355162443,mumbai,USA,East,NaN,...,8621.622057,1114.660511,Warehouse A,South Hub,Ms. Verma,Medium,UPI,Yes,Returned,No Remarks
79,S665933,O95206,C9026,Fatima Noor,john@example.com,918359928012,Bangalore,USA,North,560001.0,...,1092.005095,860.604490,NaN,South Hub,Mr. Khan,Low,Card,Yes,Returned,Check packaging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9947,S806319,O85510,C3241,Jane Smith,john@example.com,917092825637,Bangalore,USA,East,NaN,...,6853.332809,914.071878,Hub C,South Hub,Mr. Patel,High,Credit,NaN,Returned,Handle with care
9965,S496316,O60913,C2565,Amit Kumar,amit@gmail.com,917592835375,Chennai,UK,North,560001.0,...,9768.548903,1406.512023,Hub C,South Hub,Ms. Verma,NaN,Debit,NaN,Returned,Check packaging
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,5675.666106,107.634806,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,178.809623,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,5625.156091,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks

In [58]:
total_value_per_customer=(df.groupby("Customer_ID")["Total_Price"].sum().reset_index(name="Total_Value"))

In [59]:
total_value_per_customer

     Customer_ID    Total_Value
0          C1015   79017.036226
1          C1017   14882.343105
2          C1021   50746.420565
3          C1037   38876.644400
4          C1070  183930.737201
...          ...            ...
2097       C9985   65423.890909
2098       C9988   61620.033408
2099       C9991  171978.991210
2100       C9993   92774.504026
2101       C9996   78649.693299

[2102 rows x 2 columns]

In [60]:
avg_fuel_cost = (df.groupby("Delivery_Mode")["Fuel_Cost"].mean().reset_index(name="Avg_Fuel_Cost"))

In [61]:
avg_fuel_cost

  Delivery_Mode  Avg_Fuel_Cost
0           Air    5158.462025
1          Rail    5364.161772
2          Road    5215.581111
3          Ship    5334.423854
4          road    5368.094002

In [62]:
customers_multi_country = (df.groupby("Customer_ID")["Country"].nunique().reset_index(name="Country_Count").
    query("Country_Count > 1"))

In [63]:
customers_multi_country

     Customer_ID  Country_Count
24         C1186              2
34         C1217              2
51         C1275              2
83         C1376              2
91         C1397              2
...          ...            ...
2007       C9573              2
2031       C9678              2
2038       C9704              2
2063       C9818              2
2082       C9907              2

[157 rows x 2 columns]

In [64]:
vehicles_over_50 = (df.groupby("Vehicle_ID").size()
      .reset_index(name="shipment_count")
      .query("shipment_count > 5"))

In [65]:
vehicles_over_50

    Vehicle_ID  shipment_count
12        V112               6
35        V137               6
48        V151               6
53        V157               6
75        V180               6
77        V183               7
79        V185               7
97        V204               6
101       V208               8
106       V215               6
126       V235               7
142       V254               7
152       V264               6
156       V268               7
175       V287               6
192       V307               7
216       V331               6
274       V392               7
283       V402               7
284       V403               9
305       V426               6
349       V477               7
355       V483               6
360       V488               8
390       V521               7
406       V539               7
426       V559               6
467       V602               6
509       V646               7
551       V691               6
592       V736               6
600       V744               6
617       V763               6
620       V766               9
623       V769               7
642       V790               6
654       V803               7
735       V888               6
744       V897               8
768       V922               6
804       V962               6
823       V983               6

In [66]:
warehouses_multi_region = (
    df.groupby("Warehouse_Name")["Region"]
      .nunique()
      .reset_index(name="region_count")
      .query("region_count > 1"))

In [67]:
warehouses_multi_region

  Warehouse_Name  region_count
0        Central             4
1      North Hub             4
2      South Hub             4

In [68]:
df["Revenue"]=df["Quantity"]*df["Unit_Price"]

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2034081316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"]=df["Quantity"]*df["Unit_Price"]

In [69]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Distance_km,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks,Revenue
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,1009.235384,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks,24737.388485
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,65.594470,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging,21312.364345
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,738.698400,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks,50873.602704
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,151.024447,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care,17316.171940
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,490.745004,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care,47047.703879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,107.634806,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks,45251.862239
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,1134.787063,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care,56976.776093
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,1097.124418,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care,50801.857344
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,1678.080913,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks,44447.994597
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,1070.479319,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks,25333.379012

In [70]:
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
df['Shipment_Date'] = pd.to_datetime(df['Shipment_Date'])
df['Delivery_Duration'] = df['Delivery_Date'] - df['Shipment_Date']

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3608170239.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3608170239.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Shipment_Date'] = pd.to_datetime(df['Shipment_Date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3608170239.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Duration'] = df['Delivery_Date'] - df['Shipment_Date']

In [71]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Delivery_Center,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,NaN,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks,24737.388485,191 days
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Warehouse B,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging,21312.364345,1424 days
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Warehouse A,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks,50873.602704,1113 days
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,NaN,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care,17316.171940,864 days
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Warehouse B,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care,47047.703879,343 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Hub C,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks,45251.862239,863 days
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Warehouse B,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care,56976.776093,700 days
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,NaN,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care,50801.857344,1634 days
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Warehouse A,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks,44447.994597,1546 days
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Warehouse A,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks,25333.379012,768 days

In [72]:
df["Fuel_Efficiency"] = df["Distance_km"] / df["Fuel_Cost"]

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2959251268.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Fuel_Efficiency"] = df["Distance_km"] / df["Fuel_Cost"]

In [73]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Warehouse_Name,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,North Hub,Mr. Khan,High,Card,NaN,Pending,No Remarks,24737.388485,191 days,2.862874
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,North Hub,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging,21312.364345,1424 days,0.007357
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Central,Mr. Patel,Low,Debit,Yes,Pending,No Remarks,50873.602704,1113 days,0.107787
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,North Hub,NaN,Medium,Debit,NaN,Returned,Handle with care,17316.171940,864 days,0.022666
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Central,Mr. Patel,Medium,Debit,No,NaN,Handle with care,47047.703879,343 days,0.057014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,NaN,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks,45251.862239,863 days,0.018964
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,NaN,Ms. Verma,Low,Online,NaN,Returned,Handle with care,56976.776093,700 days,6.346342
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,North Hub,Ms. Verma,High,Cash,Yes,Pending,Handle with care,50801.857344,1634 days,0.355315
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Central,Mr. Patel,Medium,Card,No,Returned,No Remarks,44447.994597,1546 days,0.298317
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,NaN,Mr. Khan,High,Credit,NaN,Pending,No Remarks,25333.379012,768 days,0.139881

In [74]:
df["Profit"] = df["Total_Price"] - df["Fuel_Cost"]

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2741325043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Profit"] = df["Total_Price"] - df["Fuel_Cost"]

In [75]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Manager_Name,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,Mr. Khan,High,Card,NaN,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Mr. Khan,High,UPI,Yes,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Mr. Patel,Low,Debit,Yes,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,NaN,Medium,Debit,NaN,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Mr. Patel,Medium,Debit,No,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Ms. Verma,NaN,NaN,Yes,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Ms. Verma,Low,Online,NaN,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Ms. Verma,High,Cash,Yes,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Mr. Patel,Medium,Card,No,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Mr. Khan,High,Credit,NaN,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609

In [76]:
df["Delay_Flag"] = df["Delay_Days"].apply(lambda x: "Yes" if x > 0 else "No")

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2808876476.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Delay_Flag"] = df["Delay_Days"].apply(lambda x: "Yes" if x > 0 else "No")

In [77]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Order_Priority,Payment_Mode,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,High,Card,NaN,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,High,UPI,Yes,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Low,Debit,Yes,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Medium,Debit,NaN,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Medium,Debit,No,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,NaN,NaN,Yes,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Low,Online,NaN,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,High,Cash,Yes,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Medium,Card,No,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,High,Credit,NaN,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes

In [78]:
df["Urgency_Level"] = df["Order_Priority"].map({"High": "Urgent","Medium": "Normal","Low": "Low"})

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\930627487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Urgency_Level"] = df["Order_Priority"].map({"High": "Urgent","Medium": "Normal","Low": "Low"})

In [79]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Payment_Mode,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,Card,NaN,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,UPI,Yes,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Debit,Yes,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Debit,NaN,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Debit,No,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,NaN,Yes,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Online,NaN,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Cash,Yes,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Card,No,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Credit,NaN,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent

In [80]:
payment_map = {
    "Cash": 1,
    "Credit": 2,
    "Debit": 3,
    "UPI": 4,
    "Online": 5,
    "Card": 6}
df["Payment_Mode_Encoded"] = df["Payment_Mode"].map(payment_map)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1962486592.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Mode_Encoded"] = df["Payment_Mode"].map(payment_map)

In [81]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Insurance,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,NaN,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Yes,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Yes,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,NaN,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,No,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Yes,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,NaN
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,NaN,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Yes,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,No,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,NaN,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0

In [82]:
df["Order_Priority_Encoded"] = df["Order_Priority"].map({"High": 3,"Medium": 2,"Low": 1})

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3000936895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order_Priority_Encoded"] = df["Order_Priority"].map({"High": 3,"Medium": 2,"Low": 1})

In [83]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded
7,S734726,O77929,C3183,michael brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0
16,S694897,O55928,C7775,michael brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,NaN,NaN
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0
9987,S996729,O86227,C3986,michael brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0

In [84]:
top_10_customers = (
    df.groupby("Customer_Name", as_index=False)["Revenue"]
      .sum()
      .sort_values(by="Revenue", ascending=False)
      .head(10))

In [85]:
top_10_customers

   Customer_Name       Revenue
3       John Doe  9.143028e+06
2     Jane Smith  8.646884e+06
5  michael brown  8.627361e+06
1    Fatima Noor  8.217262e+06
0     Amit Kumar  7.824763e+06
4         Li Wei  7.259645e+06

In [86]:
top_10_cities = (
    df.groupby("City")
      .size()
      .reset_index(name="Number_of_Shipments")
      .sort_values(by="Number_of_Shipments", ascending=False)
      .head(10))

In [87]:
top_10_cities

        City  Number_of_Shipments
4    Unknown                  402
0  Bangalore                  395
1    Chennai                  390
3     Mumbai                  384
2      Delhi                  379
5     mumbai                  367

In [88]:
most_used_delivery_mode = (
    df["Delivery_Mode"]
      .value_counts().head(1))

In [89]:
most_used_delivery_mode

Delivery_Mode
Rail    478
Name: count, dtype: int64

In [90]:
df["Delivery_Mode"].mode()[0]

'Rail'

In [91]:
avg_delay_by_category = (
    df.groupby("Category", as_index=False)["Delay_Days"]
      .mean()
      .rename(columns={"Delay_Days": "Avg_Delay_Days"}))

In [92]:
avg_delay_by_category

      Category  Avg_Delay_Days
0  Accessories        6.107969
1     Clothing        6.153266
2  Electronics        6.215938
3         Food        6.188630
4    Furniture        6.268041
5         Misc        6.286885

In [93]:
top_5_products = (
    df.groupby("Product_Name", as_index=False)["Revenue"]
      .sum()
      .sort_values(by="Revenue", ascending=False)
      .head(5))

In [94]:
top_5_products

  Product_Name       Revenue
1   Headphones  1.024675e+07
3       Mobile  9.900159e+06
4       Tablet  9.768915e+06
0      Charger  9.168605e+06
2       Laptop  9.131004e+06

In [95]:
top_driver = df['Driver_Name'].value_counts().idxmax()
top_deliveries = df['Driver_Name'].value_counts().max()
print(top_driver, top_deliveries)

Mr. Rao 491

In [96]:
top_warehouse = df['Warehouse_Name'].value_counts().idxmax()
top_count = df['Warehouse_Name'].value_counts().max()
print(top_warehouse, top_count)

Central 594

In [97]:
avg_fuel_cost = df.groupby('Transport_Type')['Fuel_Cost'].mean()

In [98]:
avg_fuel_cost

Transport_Type
Bike     5360.090904
Cargo    5222.429422
Truck    5262.713554
Van      5258.537664
Name: Fuel_Cost, dtype: float64

In [99]:
avg_fuel_cost  = (df.groupby("Transport_Type", as_index=False)["Fuel_Cost"]
      .mean()
      .rename(columns={"Fuel_Cost": "Avg_Fuel_Cost"}))

In [100]:
avg_fuel_cost

  Transport_Type  Avg_Fuel_Cost
0           Bike    5360.090904
1          Cargo    5222.429422
2          Truck    5262.713554
3            Van    5258.537664

In [101]:
total_revenue = (df.groupby(['Region', 'Country'])['Revenue']
      .sum()
      .reset_index())
print(total_revenue)

   Region  Country       Revenue
0    East    India  1.847146e+06
1    East       UK  3.359408e+06
2    East      USA  3.055286e+06
3    East  Unknown  1.758118e+06
4    East    india  1.623285e+06
5   North    India  1.312711e+06
6   North       UK  3.075219e+06
7   North      USA  2.810676e+06
8   North  Unknown  1.402736e+06
9   North    india  1.773959e+06
10  South    India  1.790103e+06
11  South       UK  3.603340e+06
12  South      USA  3.196614e+06
13  South  Unknown  1.793782e+06
14  South    india  1.443028e+06
15   West    India  1.602114e+06
16   West       UK  2.529098e+06
17   West      USA  2.772050e+06
18   West  Unknown  2.093260e+06
19   West    india  1.802493e+06

In [102]:
avg_delivery_duration = (
    df.groupby('Delivery_Mode')['Delivery_Duration']
      .mean()
      .reset_index())
print(avg_delivery_duration)

  Delivery_Mode           Delivery_Duration
0           Air 687 days 09:18:56.842105264
1          Rail 727 days 08:44:11.046025104
2          Road 701 days 02:11:45.882352944
3          Ship 737 days 15:02:16.708860760
4          road           704 days 12:41:36

In [103]:
df['Customer_Name'] = (
    df['Customer_Name']
      .astype(str)
      .str.strip()
      .str.title())

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\504338674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer_Name'] = (

In [104]:
df['Delivery_Mode'] = (
    df['Delivery_Mode']
      .astype(str)
      .str.strip()
      .str.title())

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2853567666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Delivery_Mode'] = (

In [105]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded
7,S734726,O77929,C3183,Michael Brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0
16,S694897,O55928,C7775,Michael Brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,NaN,NaN
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0
9987,S996729,O86227,C3986,Michael Brown,amit@gmail.com,918314767100,Unknown,india,East,NaN,...,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0

In [106]:
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(0)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2121743050.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_cols] = df[numeric_cols].fillna(0)

In [107]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Return_Status,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded
7,S734726,O77929,C3183,Michael Brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,Pending,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Not Returned,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,Pending,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Returned,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0
16,S694897,O55928,C7775,Michael Brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,NaN,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,Returned,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,0.0,0.0
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Returned,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Pending,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0
9987,S996729,O86227,C3986,Michael Brown,amit@gmail.com,918314767100,Unknown,india,East,0.0,...,Returned,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,Pending,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0

In [108]:
mask = df["Shipment_Date"] > df["Delivery_Date"]
swapped_rows = df[mask]
df.loc[mask, ["Shipment_Date", "Delivery_Date"]] = (
    df.loc[mask, ["Delivery_Date", "Shipment_Date"]].values)

In [109]:
mask

7       False
8       False
9       False
15      False
16      False
        ...
9977    False
9980    False
9986    False
9987    False
9995    False
Length: 2317, dtype: bool

In [110]:
conflicts = df.groupby(
    ["Order_ID", "Shipment_Date"]
).filter(lambda x:x["Status"].nunique() > 1)

In [111]:
conflicts

Empty DataFrame
Columns: [Shipment_ID, Order_ID, Customer_ID, Customer_Name, Email, Phone, City, Country, Region, Postal_Code, Product_ID, Product_Name, Category, Weight_kg, Quantity, Unit_Price, Total_Price, Shipment_Date, Delivery_Date, Delay_Days, Status, Delivery_Mode, Vehicle_ID, Driver_Name, Transport_Type, Route_ID, Fuel_Cost, Distance_km, Delivery_Center, Warehouse_Name, Manager_Name, Order_Priority, Payment_Mode, Insurance, Return_Status, Remarks, Revenue, Delivery_Duration, Fuel_Efficiency, Profit, Delay_Flag, Urgency_Level, Payment_Mode_Encoded, Order_Priority_Encoded]
Index: []

[0 rows x 44 columns]

In [112]:
df["valid"] = ((df["Total_Price"] - df["Quantity"] * df["Unit_Price"]).abs() <= 0.01)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1359609902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["valid"] = ((df["Total_Price"] - df["Quantity"] * df["Unit_Price"]).abs() <= 0.01)

In [113]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded,valid
7,S734726,O77929,C3183,Michael Brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0,False
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0,False
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0,False
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0,False
16,S694897,O55928,C7775,Michael Brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,0.0,0.0,False
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0,False
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0,False
9987,S996729,O86227,C3986,Michael Brown,amit@gmail.com,918314767100,Unknown,india,East,0.0,...,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0,False
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0,False

In [114]:
import numpy as np
df=df.replace(r'^\s*$', np.nan, regex=True)

In [119]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded,valid
7,S734726,O77929,C3183,Michael Brown,amit@gmail.com,917852158344,Chennai,UK,NaN,400001.0,...,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0,False
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0,False
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0,False
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0,False
16,S694897,O55928,C7775,Michael Brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,NaN,0.0,0.0,False
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0,False
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,NaN,400001.0,...,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0,False
9987,S996729,O86227,C3986,Michael Brown,amit@gmail.com,918314767100,Unknown,india,East,0.0,...,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0,False
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,NaN,110001.0,...,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0,False

In [123]:
df["Region"].fillna("Unknown",inplace=True)

In [124]:
df["Product_Name"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\4170694032.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Product_Name"].fillna("Unknown",inplace=True)

In [125]:
df["Status"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\4223991459.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Status"].fillna("Unknown",inplace=True)

In [126]:
df["Driver_Name"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\2427605273.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Driver_Name"].fillna("Unknown",inplace=True)

In [127]:
df["Transport_Type"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1670296728.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Transport_Type"].fillna("Unknown",inplace=True)

In [129]:
df["Delivery_Center"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\921766996.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Delivery_Center"].fillna("Unknown",inplace=True)

In [131]:
df["Warehouse_Name"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\3353404119.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Warehouse_Name"].fillna("Unknown",inplace=True)

In [132]:
df["Manager_Name"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1289051196.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Manager_Name"].fillna("Unknown",inplace=True)

In [133]:
df["Order_Priority"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1479368997.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Order_Priority"].fillna("Unknown",inplace=True)

In [135]:
df["Payment_Mode"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\384303531.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Payment_Mode"].fillna("Unknown",inplace=True)

In [136]:
df["Insurance"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\1367601635.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Insurance"].fillna("Unknown",inplace=True)

In [138]:
df["Return_Status"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\4181791310.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Return_Status"].fillna("Unknown",inplace=True)

In [140]:
df["Urgency_Level"].fillna("Unknown",inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15616\491449230.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Urgency_Level"].fillna("Unknown",inplace=True)

In [141]:
df

,Shipment_ID,Order_ID,Customer_ID,Customer_Name,Email,Phone,City,Country,Region,Postal_Code,...,Remarks,Revenue,Delivery_Duration,Fuel_Efficiency,Profit,Delay_Flag,Urgency_Level,Payment_Mode_Encoded,Order_Priority_Encoded,valid
7,S734726,O77929,C3183,Michael Brown,amit@gmail.com,917852158344,Chennai,UK,Unknown,400001.0,...,No Remarks,24737.388485,191 days,2.862874,18286.959426,Yes,Urgent,6.0,3.0,False
8,S728975,O40008,C3098,Jane Smith,amit@gmail.com,918298796637,Mumbai,Unknown,East,600001.0,...,Check packaging,21312.364345,1424 days,0.007357,70100.674533,Yes,Urgent,4.0,3.0,False
9,S427342,O36381,C5569,John Doe,john@example.com,916712246490,Unknown,India,South,110001.0,...,No Remarks,50873.602704,1113 days,0.107787,83244.431990,Yes,Low,3.0,1.0,False
15,S639574,O65339,C2260,John Doe,jane@,919440752144,Unknown,Unknown,West,560001.0,...,Handle with care,17316.171940,864 days,0.022666,40512.273438,Yes,Normal,3.0,2.0,False
16,S694897,O55928,C7775,Michael Brown,jane@,918536798041,Mumbai,USA,South,400001.0,...,Handle with care,47047.703879,343 days,0.057014,139768.293485,Yes,Normal,3.0,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,S913811,O78710,C6685,Fatima Noor,amit@gmail.com,919023398511,Unknown,Unknown,South,110001.0,...,No Remarks,45251.862239,863 days,0.018964,28300.704274,Yes,Unknown,0.0,0.0,False
9980,S424262,O34605,C1678,John Doe,amit@gmail.com,917908788202,Mumbai,India,South,560001.0,...,Handle with care,56976.776093,700 days,6.346342,140866.075067,Yes,Low,5.0,1.0,False
9986,S663859,O33660,C6920,Jane Smith,john@example.com,918488133538,Bangalore,Unknown,Unknown,400001.0,...,Handle with care,50801.857344,1634 days,0.355315,130557.666148,Yes,Urgent,1.0,3.0,False
9987,S996729,O86227,C3986,Michael Brown,amit@gmail.com,918314767100,Unknown,india,East,0.0,...,No Remarks,44447.994597,1546 days,0.298317,135409.760310,Yes,Normal,6.0,2.0,False
9995,S331063,O20146,C9393,Amit Kumar,amit@gmail.com,917072100856,Chennai,USA,Unknown,110001.0,...,No Remarks,25333.379012,768 days,0.139881,89793.354609,Yes,Urgent,2.0,3.0,False

In [142]:
df.isnull().sum()

Shipment_ID               0
Order_ID                  0
Customer_ID               0
Customer_Name             0
Email                     0
Phone                     0
City                      0
Country                   0
Region                    0
Postal_Code               0
Product_ID                0
Product_Name              0
Category                  0
Weight_kg                 0
Quantity                  0
Unit_Price                0
Total_Price               0
Shipment_Date             0
Delivery_Date             0
Delay_Days                0
Status                    0
Delivery_Mode             0
Vehicle_ID                0
Driver_Name               0
Transport_Type            0
Route_ID                  0
Fuel_Cost                 0
Distance_km               0
Delivery_Center           0
Warehouse_Name            0
Manager_Name              0
Order_Priority            0
Payment_Mode              0
Insurance                 0
Return_Status             0
Remarks                   0
Revenue                   0
Delivery_Duration         0
Fuel_Efficiency           0
Profit                    0
Delay_Flag                0
Urgency_Level             0
Payment_Mode_Encoded      0
Order_Priority_Encoded    0
valid                     0
dtype: int64

In [143]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2317 entries, 7 to 9995
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Shipment_ID             2317 non-null   object
 1   Order_ID                2317 non-null   object
 2   Customer_ID             2317 non-null   object
 3   Customer_Name           2317 non-null   object
 4   Email                   2317 non-null   object
 5   Phone                   2317 non-null   int64
 6   City                    2317 non-null   object
 7   Country                 2317 non-null   object
 8   Region                  2317 non-null   object
 9   Postal_Code             2317 non-null   float64
 10  Product_ID              2317 non-null   object
 11  Product_Name            2317 non-null   object
 12  Category                2317 non-null   object
 13  Weight_kg               2317 non-null   float64
 14  Quantity                2317 non-null   float64
 15  Unit_Price              2317 non-null   float64
 16  Total_Price             2317 non-null   float64
 17  Shipment_Date           2317 non-null   datetime64[ns]
 18  Delivery_Date           2317 non-null   datetime64[ns]
 19  Delay_Days              2317 non-null   float64
 20  Status                  2317 non-null   object
 21  Delivery_Mode           2317 non-null   object
 22  Vehicle_ID              2317 non-null   object
 23  Driver_Name             2317 non-null   object
 24  Transport_Type          2317 non-null   object
 25  Route_ID                2317 non-null   object
 26  Fuel_Cost               2317 non-null   float64
 27  Distance_km             2317 non-null   float64
 28  Delivery_Center         2317 non-null   object
 29  Warehouse_Name          2317 non-null   object
 30  Manager_Name            2317 non-null   object
 31  Order_Priority          2317 non-null   object
 32  Payment_Mode            2317 non-null   object
 33  Insurance               2317 non-null   object
 34  Return_Status           2317 non-null   object
 35  Remarks                 2317 non-null   object
 36  Revenue                 2317 non-null   float64
 37  Delivery_Duration       2317 non-null   timedelta64[ns]
 38  Fuel_Efficiency         2317 non-null   float64
 39  Profit                  2317 non-null   float64
 40  Delay_Flag              2317 non-null   object
 41  Urgency_Level           2317 non-null   object
 42  Payment_Mode_Encoded    2317 non-null   float64
 43  Order_Priority_Encoded  2317 non-null   float64
 44  valid                   2317 non-null   bool
dtypes: bool(1), datetime64[ns](2), float64(13), int64(1), object(27), timedelta64[ns](1)
memory usage: 816.8+ KB
None

In [144]:
df.to_csv('logistics_dataset_cleaned.csv', index=False)